### ISSUE TITLE
Implementar front-end

### ISSUE THREAD

**Issue by rafinhadufluxo** [danielpassy/Translang-Deck#6]
Em qual línguagem/framework utilizaremos para o projeto?

**Comment by danielpassy** [comment]
React é o que eu uso, mas pode ser plain JS, ou sei lá.
Qual você prefere.

**Comment by rafinhadufluxo** [comment]
plain js nunca utilizei, so vamo!

**Comment by danielpassy** [comment]
Done https://github.com/danielpassy/Translang-deck-FrontEnd
